### ISSUE TITLE
Angels Flarestacks direction is not retained

### ISSUE THREAD

**Issue by jodokus31** [asheiduk/factorio-blueprint-decoder#11]
Great tool
I'm about to downgrade a factorio version and want to keep the changes, which I have done in the meantime

I was exporting the blueprint lib with angels/bobs entities and the flare stack direction of angels is not retained, meaning, that every instances with the fluid input are facing downwards after importing the string.

I guess, I can fix it manually, because its not too much, but I maybe it could be transferred too

edit:
same for clarifier

**Comment by jodokus31** [comment]
Here's my blueprint lib dat from version 1.1.59 zipped
[blueprint-storage.dat.zip](https://github.com/asheiduk/factorio-blueprint-decoder/files/8793321/blueprint-storage.dat.zip)

**Comment by asheiduk** [comment]
I will look into the issue.
For now you can patch the script by enabling line #1912 and commenting out the following line like this:
```
    ep_direction(stream, index, entity)
#    direction = stream.u8();
```
There seem to be some problems with rotated furnaces (which a "flare stack" is internally) in the vanilla game. I will examine the behaviour with the mod to decide what's required for a general solution.

**Comment by asheiduk** [comment]
Should work now with [50bff44](https://github.com/asheiduk/factorio-blueprint-decoder/commit/50bff449b02d46ee77dedbb0c2e444517571c30c)

**Comment by asheiduk** [comment]
Closing due to a) thumbsup from author and b) timeout.
