### ISSUE TITLE
Fails to decode blueprint library containing trains that was stored while Krastorio 2 was active

### ISSUE THREAD

**Issue by xayahxxx** [asheiduk/factorio-blueprint-decoder#12]
## Steps to reproduce (Windows 10)
1. Disable all mods
2. Activate Krastorio 2 mod
3. Create blueprint that contains a cargo wagon / fluid wagon / train locomotive and add it to the blueprint library
4. Exit game
5. Run `python .\factorio-blueprint-decoder\decode <User Home>\AppData\Roaming\Factorio\blueprint-storage.dat`

## Alternate steps to reproduce (Windows 10)
1. Disable all mods
2. Create blueprint that contains a cargo wagon / fluid wagon / train locomotive and add it to the blueprint library
3. Activate Krastorio 2 mod
4. Make any change to the blueprint library
5. Exit game.
6. Run `python .\factorio-blueprint-decoder\decode <User Home>\AppData\Roaming\Factorio\blueprint-storage.dat`

## Error message
```
Traceback (most recent call last):
  File "...\factorio-blueprint-decoder\decode", line 2879, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "...\factorio-blueprint-decoder\decode", line 2550, in parse_blueprint_library
    parse_library_objects(stream, global_index, book_item, library_version)
  File "...\factorio-blueprint-decoder\decode", line 2175, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "...\factorio-blueprint-decoder\decode", line 2636, in parse_blueprint
    parse_entities(stream, index, result)
  File "...\factorio-blueprint-decoder\decode", line 2300, in parse_entities
    handler(stream, index, entity)
  File "...\factorio-blueprint-decoder\decode", line 1308, in eh_cargo_wagon
    ep_v1_1_51_4_flag(stream, index, entity, 0x00)
  File "...\factorio-blueprint-decoder\decode", line 546, in ep_v1_1_51_4_flag
    stream.expect(expected_value)
  File "...\factorio-blueprint-decoder\decode", line 339, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x01 at position <some number>
```
("..." are paths to the checkout dir replaced by me)

## Additional Info
Since Krastorio 2 adds equipment grids to train wagons, the problem might be related to that.

**Comment by asheiduk** [comment]
Can you provide me with a `blueprint_storage.dat` file containing **only** the bad blueprints?

**Comment by asheiduk** [comment]
Sorry for the delay.

I have looked into the bytes and it seems that the offending byte is just a flag and not a guard for a complete new section of data. I have no idea what this flag means. It has no effect on the export-string.

I have committed a **temporary** fix in the branch [bugfix/krastorio-rail-vehicles](https://github.com/asheiduk/factorio-blueprint-decoder/tree/bugfix/krastorio-rail-vehicles). Can you please test it against your blueprint. SInce I have no idea about the flag it could also come up in other situations.

**Comment by xayahxxx** [comment]
Both of the error cases I described in the initial post seem to be fixed on the branch (no error is raised).

I am encountering a similar error message when trying to export my current library with lots of blueprints with full K2SE+other mods active, but I guess I'll nail it down to which mod/blueprint is causing the error and open another issue...

**Comment by asheiduk** [comment]
> I'll nail it down to which mod/blueprint is causing the error and open another issue...

The `-s/--skip-bad` option might be usefull for this :-)

**Comment by asheiduk** [comment]
I've rolled up the changes into `master`.
