### ISSUE TITLE
Encode support

### ISSUE THREAD

**Issue by Ristovski** [asheiduk/factorio-blueprint-decoder#3]
It would be nice if importing directly to `blueprint-storage.dat` was possible as well, especially since pasting very large blueprints can freeze the game.

**Comment by asheiduk** [comment]
Writing an unspecified binary format is not an easy thing to do. Much more so when the format can and does change frequently. 

On bright side: Decoding a ~128MB `*.dat` file and importing it did freeze the game for a while but the import did succeed eventually.

So: I won't work on that. But patches are welcome of course.
