### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Fr-Dae** [asheiduk/factorio-blueprint-decoder#7]
Hello, having found nowhere, neither on your git, nor on your site, nor in your project a way to contact you (email/discord) I allow myself to send you a message here
I have some problems using your project.
Could you please contact me?

dae.anthony@gmail.com
Dae#5125 (discord)

**Comment by asheiduk** [comment]
So what's the problem?

**Comment by asheiduk** [comment]
No reply neither via Email not here -- closing.
