### ISSUE TITLE
File "encode-export-string"

### ISSUE THREAD

**Issue by xy-233** [asheiduk/factorio-blueprint-decoder#8]
File "encode-export-string", line 4
    jq -c . |
            ^
SyntaxError: invalid syntax

**Comment by asheiduk** [comment]
*scratch head* Works for me.
Can you tell me more about your setup? OS, Version, Encoding, Shells, ...
And the output of `dos2unix --info encode-export-string decode-export-string decode` :-)

**Comment by asheiduk** [comment]
The exact message `SyntaxError: invalid syntax` points to Python. But `encode-export-string` is not a Python script but a shell script.
So not a bug.
