### ISSUE TITLE
KeyError on first run

### ISSUE THREAD

**Issue by flbuddymooreiv** [asheiduk/factorio-blueprint-decoder#9]
Hi, here is the stack trace. I am following your instructions from clone -> README.md -> `./decode`

If you are not maintaining, I will take a look into it. Thanks in advance!

```
buddy@darkstationmk2:~/dev/factorio-blueprint-decoder$ ./decode blueprint-storage.dat 


Traceback (most recent call last):
  File "./decode", line 3114, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2785, in parse_blueprint_library
    parse_library_objects(stream, global_index, book_item, library_version)
  File "./decode", line 2427, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "./decode", line 2930, in parse_blueprint_book
    parse_library_objects(stream, index, result, library_version)
  File "./decode", line 2427, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "./decode", line 2879, in parse_blueprint
    fixup_entity_ids(result)
  File "./decode", line 2728, in fixup_entity_ids
    walk(blueprint)
  File "./decode", line 2722, in walk
    walk(value)
  File "./decode", line 2726, in walk
    walk(value)
  File "./decode", line 2714, in walk
    it["locomotives"] = [ id_to_entity[l]["entity_number"] for l in it["locomotives"]]
  File "./decode", line 2714, in <listcomp>
    it["locomotives"] = [ id_to_entity[l]["entity_number"] for l in it["locomotives"]]
KeyError: 0
```

**Comment by flbuddymooreiv** [comment]
Commenting out the "locomotives" branch gives me a lot more output. So there is probably an edge case on train schedule format that isn't caught here? I don't know! I'm just sharing! Again, thanks in advance for all your work on this and for any attention you can give to it if possible. Best Regards!

**Comment by asheiduk** [comment]
Can you provide me with a ` blueprint-storage.dat` file containing *only* one or more of these bad blueprints?

**Comment by flbuddymooreiv** [comment]
Is there something you can suggest I add to an exception handler or whatnot that would help me with my in-place setup? It would be considerable effort to isolate the blueprint as it's in a binary file and I have no idea which one it is that i need to pare down inside the factorio binary.

**Comment by asheiduk** [comment]
You can use the `-d` (or `-v`) and `-s` options: `-d` shows the names of the blueprint-books and blueprints, `-s` skips unparsable blueprints with an `ERROR` message. Delete the good blueprints from within the game -- after you have backuped your original file of course :-)

**Comment by asheiduk** [comment]
@flbuddymooreiv Are there news? Do you need more help?

**Comment by flbuddymooreiv** [comment]
Hi thanks for following up. I was playing around with the debug flag and adding some debug output and just to be some mix of difficult and curious, is this something you can work with?:
[failbp.json.txt](https://github.com/asheiduk/factorio-blueprint-decoder/files/8445986/failbp.json.txt)

**Comment by asheiduk** [comment]
Not really for several reasons:
- Your Semi-JSON shows that there is a schedules stored in the blueprint. But the blueprint does not seem to  contain any locomotive/train to which this schedule can be applied. Also the IDs of the 4 (!) locomotives in the schedule are just `0`. So the binary blueprint seems quite bogus to me.
- I'd like to examine the binary file.  That might contain more clues whether this is a systematic error or something a mod has done or some conversion process which happened during updates of the game or ...
- When I change the code I would prefer to construct some testcases for the regression tests therefore I have to reproduce that error somehow.
- I also need to know what game does when such a blueprint is exported into a blueprint string: Is there an error, is the faulty schedule omitted or copied into the output and if so with or without the zeroed IDs for the locomotives.

So the best way to help me is to provide a stripped down `blueprint-storage.dat` file containing just the faulty blueprints.

**Comment by flbuddymooreiv** [comment]
Thank you for clarification.

Perhaps there is some more investigation to do but here is the blueprint-storage.dat encoded in base64 so it can be uploaded here. It seems to run alright. Perhaps I have the wrong BP. I'll do a more exhaustive search soon but at least I have some more avenues to try now.

[blueprint-storage.dat.base64.txt](https://github.com/asheiduk/factorio-blueprint-decoder/files/8455814/blueprint-storage.dat.base64.txt).

**Comment by flbuddymooreiv** [comment]
Okay, success! I was able to recreate with only the blueprint in the dat by itself. Here it is! Let me know if you have any trouble unrolling it. For whatever it's worth, it seems like export BP from game and reimport into blank blueprint-storage does not recreate the problem, but it does appear preserved inside this dat.

Thanks in advance!
[blueprint-storage.singlebp.dat.base64.txt](https://github.com/asheiduk/factorio-blueprint-decoder/files/8456247/blueprint-storage.singlebp.dat.base64.txt)

**Comment by asheiduk** [comment]
Thank you for the file! I will debug it next Monday.

**Comment by asheiduk** [comment]
I've commited a patch which works for your `blueprint-storage.singlebp.dat.base64.txt` file (which -- funnily enough -- contains more blueprints then the previous file but also produces the bug :-) 
I still cannot recreate the situation from scratch which impedes creating a neat testcase. But I can strip down your example to just one blueprint containing just one powerpole, so I will tinker a little bit with that.

**Comment by flbuddymooreiv** [comment]
Great. What fun! Thank you for your help. I will try the patch and let you
know how it goes.

**Comment by flbuddymooreiv** [comment]
As far as I can tell, it worked!

```
$ ./decode blueprint-storage.dat > blueprints-fixed.json
$ jq '.blueprint_book.blueprints | length' blueprints-fixed.json 
908
```

Thank you for your help! Take care :)
